sudo: required
services:
  -docker

  before_install:

    - docker build -t habtayfilmon/docker-react -f Dockerfile.dev

  script:

    - docker run habtayfilmon/docker-react npm run test -- --coverage